"""add requests balance

Revision ID: 44d45e22761f
Revises: 7084bb329481
Create Date: 2025-04-17 12:05:00.427996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d45e22761f'
down_revision = '7084bb329481'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('requests_available', sa.Integer(), nullable=False))
    op.add_column('tariffs', sa.Column('requests_balance', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tariffs', 'requests_balance')
    op.drop_column('subscriptions', 'requests_available')
    # ### end Alembic commands ###
