"""add payment

Revision ID: 565d52929f56
Revises: 90a2c5178f62
Create Date: 2025-05-02 13:53:31.676743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '565d52929f56'
down_revision = '90a2c5178f62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('user_telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('cloudpayments_transaction_id', sa.BIGINT(), nullable=False),
    sa.Column('cloudpayments_subscription_id', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_telegram_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.drop_constraint('referrals_partner_id_fkey', 'referrals', type_='foreignkey')
    op.create_foreign_key(None, 'referrals', 'partners', ['partner_id'], ['id'], ondelete='CASCADE')
    op.add_column('subscriptions', sa.Column('cloudpayments_subscription_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'cloudpayments_subscription_id')
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.create_foreign_key('referrals_partner_id_fkey', 'referrals', 'partners', ['partner_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
