"""tariff tracking report

Revision ID: 7084bb329481
Revises: 94377fa65e82
Create Date: 2025-04-10 09:58:12.627508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7084bb329481'
down_revision = '94377fa65e82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariffs', sa.Column('tracking_report_interval', sa.String(), nullable=False))
    op.drop_column('tariffs', 'payment_interval')
    op.drop_column('tariffs', 'payment_period')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariffs', sa.Column('payment_period', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tariffs', sa.Column('payment_interval', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tariffs', 'tracking_report_interval')
    # ### end Alembic commands ###

