"""Add partner creator

Revision ID: 90a2c5178f62
Revises: be6bba2057a0
Create Date: 2025-04-22 17:34:57.662011

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90a2c5178f62"
down_revision = "be6bba2057a0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("partners", sa.Column("creator_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "partners", "accounts", ["creator_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "partners", type_="foreignkey")
    op.drop_column("partners", "creator_id")
    # ### end Alembic commands ###
