"""subscription with tracking

Revision ID: 94377fa65e82
Revises: 689b8a607fba
Create Date: 2025-04-09 14:42:43.052513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94377fa65e82'
down_revision = '689b8a607fba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('tracking_username', sa.String(), nullable=True))
    op.drop_column('trackings', 'approved')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackings', sa.Column('approved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('subscriptions', 'tracking_username')
    # ### end Alembic commands ###
