"""Add accounts

Revision ID: be6bba2057a0
Revises: 44d45e22761f
Create Date: 2025-04-22 17:00:10.481612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6bba2057a0'
down_revision = '44d45e22761f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('access_to_statistics', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('access_to_users', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('access_to_trackings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('access_to_partners', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('access_to_experiments', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###

