"""add media

Revision ID: 5014b91c1304
Revises: 4b9c1fa6c56f
Create Date: 2025-03-26 22:04:40.005341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5014b91c1304'
down_revision = '4b9c1fa6c56f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_medias',
    sa.Column('creator_telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('instagram_username', sa.String(), nullable=False),
    sa.Column('instagram_id', sa.String(), nullable=False),
    sa.Column('caption_text', sa.String(), nullable=True),
    sa.Column('display_uri', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_telegram_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creator_telegram_id', 'instagram_username', 'instagram_id', name='tracking_media_uq')
    )
    op.create_index(op.f('ix_tracking_medias_id'), 'tracking_medias', ['id'], unique=False)
    op.create_index(op.f('ix_tracking_medias_instagram_username'), 'tracking_medias', ['instagram_username'], unique=False)
    op.create_index(op.f('ix_trackings_creator_telegram_id'), 'trackings', ['creator_telegram_id'], unique=False)
    op.create_index(op.f('ix_trackings_instagram_username'), 'trackings', ['instagram_username'], unique=False)
    op.create_unique_constraint('tracking_uq', 'trackings', ['creator_telegram_id', 'instagram_username'])
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_constraint('tracking_uq', 'trackings', type_='unique')
    op.drop_index(op.f('ix_trackings_instagram_username'), table_name='trackings')
    op.drop_index(op.f('ix_trackings_creator_telegram_id'), table_name='trackings')
    op.drop_index(op.f('ix_tracking_medias_instagram_username'), table_name='tracking_medias')
    op.drop_index(op.f('ix_tracking_medias_id'), table_name='tracking_medias')
    op.drop_table('tracking_medias')
    # ### end Alembic commands ###
